version: '3'
services:
  shared:
    build:
      context: ./packages/shared
      dockerfile: Dockerfile    
    image: edts-shared:latest   

  host:
    build:
      context: ./packages/host
      dockerfile: Dockerfile
      args:
        - ENVIRONTMENT=staging
    image: edts-host:latest
    depends_on:
      - shared
    ports:
      - 4200:4200


  product:
    build:
      context: ./packages/product
      dockerfile: Dockerfile
      args:
        - ENVIRONTMENT=staging
    image: edts-product:latest
    depends_on:
      - host
    ports:
      - 4201:4201
