import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner/Banner'
import NavBar from '../components/Navbar/Navbar'
import Sections from '../components/Section/Section'
import styles from '../styles/Home.module.css'
import dataPopular from '../data/popular.json'
export default function Home() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.sectionWrapper}>
        <NavBar
          username={"Alfian@pcl.com"}
        />
        <Banner
          videoId="1122362"
          title="Clifford the red dog"
          subTitle="a very cute dog"
          imgUrl="/static/clifford.webp"
        />
        <div className={styles.sectionWrapper}>
          <Sections
            title="Popular"
            videos={dataPopular?.results.slice(0,11)}
          />
        </div>
        
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
